AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Size:
    Type: Number
    Description: Size of volume in GB
    Default: 8

Resources:
  EBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1a
      Encrypted: No
      Size: !Ref Size
      Tags:
        - Key: "service"
          Value: "jenkins"
        - Key: "environment"
          Value: "ci"
      VolumeType: gp2

  DLMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
              - "ec2.amazonaws.com"
          Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "dlmservice"
          PolicyDocument:
            Statement:
              - Effect: "Allow"
                Action:
                  - ec2:CreateSnapshot
                  - ec2:CopySnapshot
                  - ec2:DeleteSnapshot
                  - ec2:ImportSnapshot
                  - ec2:DescribeSnapshots
                  - ec2:DescribeSnapshotAttribute
                  - ec2:DescribeVolumes
                  - ec2:DescribeVolumeAttribute
                  - ec2:DescribeVolumeStatus
                  - ec2:DescribeVolumesModifications
                  - ec2:DescribeTags
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - ec2:CreateTags
                Resource: "arn:aws:ec2:*::snapshot/*"

  BasicLifecyclePolicy:
    Type: "AWS::DLM::LifecyclePolicy"
    Properties:
      Description: "Lifecycle Policy for Jenkins"
      ExecutionRoleArn: !GetAtt DLMRole.Arn
      State: "ENABLED"
      PolicyDetails:
        ResourceTypes:
          - "VOLUME"
        TargetTags:
          - Key: "service"
            Value: "jenkins"
<<<<<<< HEAD

=======
          - Key: "environment"
            Value: "ci"
>>>>>>> 4e0e12fb7db53dea8f9e4856323fbd3c54a1cfe8
        Schedules:
          -
            Name: "Daily Snapshots"
            TagsToAdd:
<<<<<<< HEAD
              -
                Key: "type"
=======
              - Key: "type"
>>>>>>> 4e0e12fb7db53dea8f9e4856323fbd3c54a1cfe8
                Value: "DailySnapshot"

            CreateRule:
              Interval: 24
              IntervalUnit: "HOURS"
              Times:
                - "01:00"
            RetainRule:
              Count: 5
<<<<<<< HEAD
            CopyTags: true
=======
            CopyTags: true
>>>>>>> 4e0e12fb7db53dea8f9e4856323fbd3c54a1cfe8
