AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of the SSH keypair to use for the EC2 instances.
    Default: 30deysdevops

  VPCStackName:
    Type: String
    Default: ProjectVPC
    MinLength: 1

  InstanceType:
    Type: String
    Description: Type of EC2 instance
    Default: t3.large
    ConstraintDescription: Must be a valid EC2 instance type.

  S3Path:
    Type: String
    Description: The S3 path
    Default: 30daysdevops

  SSLCertificate:
    Type: String
    Default: 'arn:aws:acm:us-east-1:230883561944:certificate/79616372-c929-4269-b861-dde983e0fb34'
    Description: ARN of Certificate attached to ELB

  DatadogSecretName:
    Type: String
    Description: Secret Name in SecretManager to extract Datadog API key
    Default: datadog_api_key

  DNSName:
    Type: String
    Description: DNS subdomain name for Jenkins
    Default: ci

  R53HostedZone:
    Type: String
    Default: '30daystodevops.me.uk.'
    Description: Base DNS domain name
        
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0ff8a91507f77f867

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:
        - PolicyName: EC2
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - iam:CreateInstanceProfile
                  - iam:CreateRole
                  - iam:DeleteRolePolicy
                  - iam:PutRolePolicy
                  - autoscaling:CreateLaunchConfiguration
                  - autoscaling:DescribeLaunchConfigurations
                  - autoscaling:CreateAutoScalingGroup
                  - autoscaling:UpdateAutoScalingGroup
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeScalingActivities
                  - autoscaling:PutScalingPolicy
                  - ec2:DescribeTags
                  - ec2:DescribeSnapshots
                  - ec2:DescribeVolumes
                  - ec2:DescribeAddresses
                  - ec2:DescribeKeyPairs
                  - ec2:CreateVolume
                  - ec2:CreateTags
                  - ec2:AttachVolume
                  - ec2:AssociateAddress
                  - ec2:CreateSecurityGroup
                  - ec2:DescribeSecurityGroups
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:DescribeAccountAttributes
                  - iam:AddRoleToInstanceProfile
                  - iam:PassRole
                  - secretsmanager:GetSecretValue
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:GetRepositoryPolicy
                  - ecr:DescribeRepositories
                  - ecr:ListImages
                  - ecr:DescribeImages
                  - ecr:BatchGetImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                  - cloudformation:DescribeStacks
                  - cloudwatch:PutMetricAlarm
                  - rds:CreateDBSubnetGroup
                  - rds:DescribeDBSubnetGroups
                  - rds:DescribeAccountAttributes
                  - rds:DescribeCertificates
                  - rds:DescribeDBClusterSnapshots
                  - rds:DescribeDBInstances
                  - rds:CreateDBInstance
                  - rds:DescribeEngineDefaultClusterParameters
                  - rds:DescribeEngineDefaultParameters
                  - rds:DescribeEventCategories
                  - rds:DescribeEvents
                  - rds:DescribeOptionGroupOptions
                  - rds:DescribeOrderableDBInstanceOptions
                  - rds:DownloadCompleteDBLogFile
                  - rds:PurchaseReservedDBInstancesOffering
                  - cloudwatch:DeleteAlarm
                  - autoscaling:DeletePolicy
                  - autoscaling:DeleteAutoScalingGroup
                  - autoscaling:DeleteLaunchConfiguration
                  - iam:RemoveRoleFromInstanceProfile
                  - ec2:DeleteSecurityGroup
                  - iam:DeleteRole
                  - iam:*


  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: InstanceRole

  SimpleConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      IamInstanceProfile: !Ref InstanceProfile
      KeyName: !Ref KeyPairName
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      InstanceType: !Ref InstanceType
      AssociatePublicIpAddress: True
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -o errexit
          set -o nounset
          set -o xtrace

          aws s3 cp "s3://${S3Path}/scripts/jenkins/install.sh" - |       \
            bash -l -s --                                                 \
            --datadog-secret-name "${DatadogSecretName}"                  \
            --hostname jenkins

          echo $(date): Finished installing Jenkins

  MyServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      Tags:
        - Key: 'service'
          Value: 'jenkins'
          PropagateAtLaunch: true

      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "${VPCStackName}-PublicSubnet0"
      LaunchConfigurationName: !Ref SimpleConfig
      MinSize: '1'
      MaxSize: '1'
      LoadBalancerNames:
        - Ref: JenkinsLoadBalancer

  JenkinsLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Subnets:
        - Fn::ImportValue: !Sub "${VPCStackName}-PublicSubnet0"
      SecurityGroups:
        - Ref: LBSecurityGroup
      Listeners:
        - InstancePort: 8080
          LoadBalancerPort: 80
          Protocol: HTTP
        - InstancePort: 8080
          InstanceProtocol: HTTP
          LoadBalancerPort: 443
          Protocol: HTTPS
          SSLCertificateId: !Ref SSLCertificate
      Tags:
        - Key: 'service'
          Value: 'jenkins'
        - Key: 'resource'
          Value: 'ELB'

  R53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref R53HostedZone
      Name: !Join ['', [ !Ref DNSName, ., !Ref R53HostedZone]]
      Type: CNAME
      TTL: 300
      ResourceRecords: [ !GetAtt JenkinsLoadBalancer.DNSName ]

  InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        VpcId:
          Fn::ImportValue: !Sub "${VPCStackName}-VPCId"
        GroupDescription: SSH, HTTP
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  LBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${VPCStackName}-VPCId"
      GroupDescription: HTTP, HTTPS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
