version: '2'
services:
  jenkins:
    image: 'jenkinsci/blueocean'
    user: root
    labels:
      kompose.service.type: nodeport
      com.datadoghq.ad.logs: '[{"source": "java", "service": "myapp", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    ports:
      - '8080:8080'
    #      - '443:8443'
    #      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/jenkins:/var/jenkins_home