version: '2'
services:
  jenkins:
    image: 'jenkinsci/blueocean'
    user: root
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
    #      - '443:8443'
    #      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/jenkins:/var/jenkins_home