AWSTemplateFormatVersion: '2010-09-09'
################################################################################
# Parameters
################################################################################
Parameters:
  Environment:
    Type: String
    Description: Environment (qa, prod).
    AllowedValues: [qa, prod]
    ConstraintDescription: Must be a valid environment name
  Name:
    Type: String
    Default: nick
    MaxLength: 50     # optional
    MinLength: 1     # optional
  VPCStackName:
    Type: String
    Default: ProjectVPC
    MinLength: 1

################################################################################
# Resources
################################################################################
Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      # SecurityGroups: [!Ref HTTPSecurityGroup]
#      AvailabilityZones:
#        Fn::GetAZs: ''
      Subnets:
        - Fn::ImportValue: !Sub "${VPCStackName}-PrivateSubnet0"
      Listeners:
        - InstancePort: 80
          LoadBalancerPort: 80
          Protocol: HTTP
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '2'
      Tags:
      - Key: 'Name'
        Value: !Ref Name

Outputs:
  LoadBalancerID:
    Description: Apps LoadBalancer ID
    Value: !Ref LoadBalancer
    Export:
      Name: !Sub "${AWS::StackName}-LoadBalancerID"
