AWSTemplateFormatVersion: '2010-09-09'
################################################################################
# Parameters
################################################################################
Parameters:
  ELBStackName:
    Type: String
    Default: app-ELB
    MinLength: 1

  VPCStackName:
    Type: String
    Default: ProjectVPC
    MinLength: 1

  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Default: 30deysdevops

  Environment:
    Type: String
    Description: Environment (qa, prod).
    AllowedValues: [qa, prod]
    ConstraintDescription: Must be a valid environment name
    Default: qa

  Name:
    Type: String
    Default: app
    MaxLength: 50     # optional
    MinLength: 1     # optional

  Version:
    Type: String

################################################################################
# Mappings
################################################################################
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0080e4c5bc078760e

################################################################################
# Resources
################################################################################
Resources:
  WebLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      SecurityGroups: [!Ref SSHSecurityGroup, !Ref HTTPSecurityGroup]
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      IamInstanceProfile: !Ref InstanceProfile
      AssociatePublicIpAddress: no
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          sudo yum install -y aws-cfn-bootstrap
          sudo /opt/aws/bin/cfn-init -v                            \
               --stack ${AWS::StackName}-${Environment}-${Version} \
               --resource WebLaunchConfig                          \
               --region ${AWS::Region}

          /opt/aws/bin/cfn-signal -e $?                            \
               --stack ${AWS::StackName}-${Environment}-${Version} \
               --resource WebServerGroup                           \
               --region ${AWS::Region}

          aws s3 cp s3://30daysdevops/nick/app.pp ./ && \
            sudo /opt/puppetlabs/bin/puppet apply app.pp

          /opt/aws/bin/cfn-signal -e $?                            \
               --stack ${AWS::StackName}-${Environment}-${Version} \
               --resource WebServerGroup                           \
               --region ${AWS::Region}
    Metadata:
      "AWS::CloudFormation::Init":
          config:
            packages:
              rpm:
                puppet: "https://yum.puppet.com/puppet5/puppet5-release-el-6.noarch.rpm"
              yum:
                puppet-agent: []

  WebServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: 
        - Fn::ImportValue: !Sub "${VPCStackName}-PrivateSubnet0"
      LaunchConfigurationName: !Ref WebLaunchConfig
      LoadBalancerNames:
        - Fn::ImportValue: !Sub "${ELBStackName}-LoadBalancerID"
      HealthCheckType: ELB
      HealthCheckGracePeriod: 120
      MinSize: '1'
      MaxSize: '5'
      Cooldown: 60
      DesiredCapacity: 1
      Tags:
        - Key: 'Name'
          Value: !Ref Name
          PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Count: 2
        Timeout: "PT5M"

  WebServerScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref WebServerGroup
      Cooldown: 60
      ScalingAdjustment: 1

  WebServerScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref WebServerGroup
      Cooldown: 60
      ScalingAdjustment: -1

  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Scale-up if CPU > 90% for 10 minutes"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 75
      AlarmActions: [ !Ref WebServerScaleUpPolicy ]
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref WebServerGroup
      ComparisonOperator: GreaterThanThreshold

  CPUAlarmLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
     AlarmDescription: "Scale-down if CPU < 70% for 10 minutes"
     MetricName: CPUUtilization
     Namespace: AWS/EC2
     Statistic: Average
     Period: 300
     EvaluationPeriods: 2
     Threshold: 50
     AlarmActions: [ !Ref WebServerScaleDownPolicy ]
     Dimensions:
       - Name: AutoScalingGroupName
         Value: !Ref WebServerGroup
     ComparisonOperator: LessThanThreshold

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: EC2
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - s3:GetObject
                  - secretsmanager:GetSecretValue

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: InstanceRole

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId:
        Fn::ImportValue: !Sub "${VPCStackName}-VPCId"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80
      VpcId: 
        Fn::ImportValue: !Sub "${VPCStackName}-VPCId"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
